CREATE (LandCorpHoldings:Organisation { name: "LandCorpHoldings"})
CREATE (LandCorpAjax:Organisation { name: "LandCorpAjax"})-[:HOLDING]->(LandCorpHoldings)
CREATE (LandCorpAoraki:Organisation { name: "LandCorpAjax"})-[:HOLDING]->(LandCorpHoldings)
CREATE (be1:BillingEntity { name: "BE_LandCorpHoldings"})-[:FINANCIAL_ACCT]->(LandCorpHoldings)
CREATE (p1:Person { name: "Person 1"})-[:MEMBERSHIP]->(LandCorpHoldings)
CREATE (p2:Person { name: "Person 2"})-[:MEMBERSHIP]->(LandCorpAjax)
CREATE (p3:Person { name: "Person 3"})-[:MEMBERSHIP]->(LandCorpAoraki)

CREATE (ao1:AgriculturalOperation { name: "Ag Op Ajax"})
CREATE (ao2:AgriculturalOperation { name: "Ag Op Aoraki"})
CREATE (LandCorpAjax)-[:FARMING_OPERATION]->(ao1)
CREATE (LandCorpAoraki)-[:FARMING_OPERATION]->(ao2)

CREATE (ag1:AnimalGroup { name: "Ag Ajax"})
CREATE (ag2:AnimalGroup { name: "Ag Aoraki"})
CREATE (ao1)-[:ANIMAL_MANAGEMENT]->(ag1)
CREATE (ao2)-[:ANIMAL_MANAGEMENT]->(ag2)
